### PR TITLE
Debugging travis config

### PR DESCRIPTION
**Pull request by ExpHP**
Let's see if this "fixes" the stalled CI tests.

### CODE REVIEW

**Comment by ExpHP** [comment]
Uhhhhhhhhhhhhhhh.

Contrary to what the CI says, I *don't* think this succeeded...

```
Timeout (20 minutes) reached. Terminating "./travis-after-success"
The command ./travis-after-success exited with 137.
```

There was also no output.  It's almost as though the `set -xe` didn't do anything...

**Comment by lloydmeta** [comment]
I've merged https://github.com/lloydmeta/frunk/pull/136 for now to unblock #134; we can keep this PR open to explore more fine-grained solutions :)

**Comment by ExpHP** [comment]
To copy my comment on that PR for ease of bookkeeping (since this one is open and that one is merged), the current fix on master does not actually run the benches because it dies in the script. (and travis ignores exit codes in `after_success`)

**Comment by ExpHP** [comment]
Closing.  To my knowledge, frunk has fully migrated from Travis CI to Github Actions.

**Pull request closed without merging**
