### PR TITLE
Debug impls should use DebugStruct

### PR DESCRIPTION
**Pull request by ExpHP**
Just best practices; Debug impls should use the helpers on `fmt::Formatter` when possible in order to properly support `{:#?}`.

### CODE REVIEW

**Comment by lloydmeta** [comment]
I think after the conflicts in this one are fixed + merged, with #148 and #152, we have (more than) enough for a new minor-version-bumped release.

**Comment by ExpHP** [comment]
This has to be a major version bump because of the change to features in the `no_std` PR.  For instance, somebody could be using Validated with `default_features = false`.

For that reason, I also want to close at least #138 which seems easy enough.

**Comment by lloydmeta** [comment]
> The next release has to be a major version bump because of the change to features in the `no_std` PR. For instance, somebody could be using Validated with `default_features = false`.
> 
> For that reason, I also want to close at least #138 which seems easy enough.

🤦‍♂️ yes of course you're right; it needs to be a major bump.

**Comment by lloydmeta** [comment]
Hmm, actually no, I think since we are in x.y.z where x < 0 world, we are ok with just bumping the minor, even with a breaking change, and leaving a note

* https://semver.org/
  >  Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
* https://github.com/semver/semver/issues/333

Staying with a minor version bump seems more preferable to me than force-introducing a 1.x.x which has major implications.

**Comment by ExpHP** [comment]
To be clear, that's what I meant by a major version bump.  (I meant a bump of the first nonzero part of the version number)

**Pull request merged**
